//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaVantage.Utilities.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MongoDbCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MongoDbCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaVantage.Utilities.Common.MongoDbCommon", typeof(MongoDbCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD.
        /// </summary>
        public static string CollectionADName {
            get {
                return ResourceManager.GetString("CollectionADName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADOSC.
        /// </summary>
        public static string CollectionADOSCName {
            get {
                return ResourceManager.GetString("CollectionADOSCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADX.
        /// </summary>
        public static string CollectionADXName {
            get {
                return ResourceManager.GetString("CollectionADXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADXR.
        /// </summary>
        public static string CollectionADXRName {
            get {
                return ResourceManager.GetString("CollectionADXRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APO.
        /// </summary>
        public static string CollectionAPOName {
            get {
                return ResourceManager.GetString("CollectionAPOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AROON.
        /// </summary>
        public static string CollectionAROONName {
            get {
                return ResourceManager.GetString("CollectionAROONName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AROONOSC.
        /// </summary>
        public static string CollectionAROONOSCName {
            get {
                return ResourceManager.GetString("CollectionAROONOSCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATR.
        /// </summary>
        public static string CollectionATRName {
            get {
                return ResourceManager.GetString("CollectionATRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBANDS.
        /// </summary>
        public static string CollectionBBANDSName {
            get {
                return ResourceManager.GetString("CollectionBBANDSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOP.
        /// </summary>
        public static string CollectionBOPName {
            get {
                return ResourceManager.GetString("CollectionBOPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCI.
        /// </summary>
        public static string CollectionCCIName {
            get {
                return ResourceManager.GetString("CollectionCCIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMO.
        /// </summary>
        public static string CollectionCMOName {
            get {
                return ResourceManager.GetString("CollectionCMOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEMA.
        /// </summary>
        public static string CollectionDEMAName {
            get {
                return ResourceManager.GetString("CollectionDEMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX.
        /// </summary>
        public static string CollectionDXName {
            get {
                return ResourceManager.GetString("CollectionDXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMA.
        /// </summary>
        public static string CollectionEMAName {
            get {
                return ResourceManager.GetString("CollectionEMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equities.
        /// </summary>
        public static string CollectionEquitiesName {
            get {
                return ResourceManager.GetString("CollectionEquitiesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_DCPERIOD.
        /// </summary>
        public static string CollectionHT_DCPERIODName {
            get {
                return ResourceManager.GetString("CollectionHT_DCPERIODName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_DCPHASE.
        /// </summary>
        public static string CollectionHT_DCPHASEName {
            get {
                return ResourceManager.GetString("CollectionHT_DCPHASEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_PHASOR.
        /// </summary>
        public static string CollectionHT_PHASORName {
            get {
                return ResourceManager.GetString("CollectionHT_PHASORName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_SINE.
        /// </summary>
        public static string CollectionHT_SINEName {
            get {
                return ResourceManager.GetString("CollectionHT_SINEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_TRENDLINE.
        /// </summary>
        public static string CollectionHT_TRENDLINEName {
            get {
                return ResourceManager.GetString("CollectionHT_TRENDLINEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HT_TRENDMODE.
        /// </summary>
        public static string CollectionHT_TRENDMODEName {
            get {
                return ResourceManager.GetString("CollectionHT_TRENDMODEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAMA.
        /// </summary>
        public static string CollectionKAMAName {
            get {
                return ResourceManager.GetString("CollectionKAMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACDEXT.
        /// </summary>
        public static string CollectionMACDEXTName {
            get {
                return ResourceManager.GetString("CollectionMACDEXTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACD.
        /// </summary>
        public static string CollectionMACDName {
            get {
                return ResourceManager.GetString("CollectionMACDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAMA.
        /// </summary>
        public static string CollectionMAMAName {
            get {
                return ResourceManager.GetString("CollectionMAMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFI.
        /// </summary>
        public static string CollectionMFIName {
            get {
                return ResourceManager.GetString("CollectionMFIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDPOINT.
        /// </summary>
        public static string CollectionMIDPOINTName {
            get {
                return ResourceManager.GetString("CollectionMIDPOINTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDPRICE.
        /// </summary>
        public static string CollectionMIDPRICEName {
            get {
                return ResourceManager.GetString("CollectionMIDPRICEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUS_DI.
        /// </summary>
        public static string CollectionMINUS_DIName {
            get {
                return ResourceManager.GetString("CollectionMINUS_DIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINUS_DM.
        /// </summary>
        public static string CollectionMINUS_DMName {
            get {
                return ResourceManager.GetString("CollectionMINUS_DMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOM.
        /// </summary>
        public static string CollectionMOMName {
            get {
                return ResourceManager.GetString("CollectionMOMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string CollectionName {
            get {
                return ResourceManager.GetString("CollectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATR.
        /// </summary>
        public static string CollectionNATRName {
            get {
                return ResourceManager.GetString("CollectionNATRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBV.
        /// </summary>
        public static string CollectionOBVName {
            get {
                return ResourceManager.GetString("CollectionOBVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUS_DI.
        /// </summary>
        public static string CollectionPLUS_DIName {
            get {
                return ResourceManager.GetString("CollectionPLUS_DIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUS_DM.
        /// </summary>
        public static string CollectionPLUS_DMName {
            get {
                return ResourceManager.GetString("CollectionPLUS_DMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPO.
        /// </summary>
        public static string CollectionPPOName {
            get {
                return ResourceManager.GetString("CollectionPPOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROC.
        /// </summary>
        public static string CollectionROCName {
            get {
                return ResourceManager.GetString("CollectionROCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROCR.
        /// </summary>
        public static string CollectionROCRName {
            get {
                return ResourceManager.GetString("CollectionROCRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSI.
        /// </summary>
        public static string CollectionRSIName {
            get {
                return ResourceManager.GetString("CollectionRSIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        public static string CollectionSARName {
            get {
                return ResourceManager.GetString("CollectionSARName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMA.
        /// </summary>
        public static string CollectionSMAName {
            get {
                return ResourceManager.GetString("CollectionSMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCHF.
        /// </summary>
        public static string CollectionSTOCHFName {
            get {
                return ResourceManager.GetString("CollectionSTOCHFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCH.
        /// </summary>
        public static string CollectionSTOCHName {
            get {
                return ResourceManager.GetString("CollectionSTOCHName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOCHRSI.
        /// </summary>
        public static string CollectionSTOCHRSIName {
            get {
                return ResourceManager.GetString("CollectionSTOCHRSIName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T3.
        /// </summary>
        public static string CollectionT3Name {
            get {
                return ResourceManager.GetString("CollectionT3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMA.
        /// </summary>
        public static string CollectionTEMAName {
            get {
                return ResourceManager.GetString("CollectionTEMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANGE.
        /// </summary>
        public static string CollectionTRANGEName {
            get {
                return ResourceManager.GetString("CollectionTRANGEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMA.
        /// </summary>
        public static string CollectionTRIMAName {
            get {
                return ResourceManager.GetString("CollectionTRIMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIX.
        /// </summary>
        public static string CollectionTRIXName {
            get {
                return ResourceManager.GetString("CollectionTRIXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ULTOSC.
        /// </summary>
        public static string CollectionULTOSCName {
            get {
                return ResourceManager.GetString("CollectionULTOSCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VWAP.
        /// </summary>
        public static string CollectionVWAPName {
            get {
                return ResourceManager.GetString("CollectionVWAPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WILLR.
        /// </summary>
        public static string CollectionWILLRName {
            get {
                return ResourceManager.GetString("CollectionWILLRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMA.
        /// </summary>
        public static string CollectionWMAName {
            get {
                return ResourceManager.GetString("CollectionWMAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlphaVantageDb.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
    }
}
