//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaVantage.Utilities.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemConfigRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemConfigRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaVantage.Utilities.Common.SystemConfigRes", typeof(SystemConfigRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        public static string AppSettingsFileName {
            get {
                return ResourceManager.GetString("AppSettingsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionStrings:AvMongoConnection.
        /// </summary>
        public static string AvConnectionStringKey {
            get {
                return ResourceManager.GetString("AvConnectionStringKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings:MongoDbName.
        /// </summary>
        public static string MongoDbNameKey {
            get {
                return ResourceManager.GetString("MongoDbNameKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings:NlogConfigFileName.
        /// </summary>
        public static string NlogTaskFileName {
            get {
                return ResourceManager.GetString("NlogTaskFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appSettings:ScheduledTaskConfigFileName.
        /// </summary>
        public static string ScheduledTaskFileName {
            get {
                return ResourceManager.GetString("ScheduledTaskFileName", resourceCulture);
            }
        }
    }
}
