//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaVantage.Common.Models.TimeSeries.Daily {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvDailyTimeSeriesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvDailyTimeSeriesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaVantage.Common.Models.TimeSeries.Daily.AvDailyTimeSeriesRes", typeof(AvDailyTimeSeriesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd hh:mm:ss.
        /// </summary>
        public static string MetaDataDateTimeFormat {
            get {
                return ResourceManager.GetString("MetaDataDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Information.
        /// </summary>
        public static string MetaDataInformationTag {
            get {
                return ResourceManager.GetString("MetaDataInformationTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Last Refreshed.
        /// </summary>
        public static string MetaDataLastRefreshedTag {
            get {
                return ResourceManager.GetString("MetaDataLastRefreshedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. Output Size.
        /// </summary>
        public static string MetaDataOutputSizeTag {
            get {
                return ResourceManager.GetString("MetaDataOutputSizeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Symbol.
        /// </summary>
        public static string MetaDataSymbolTag {
            get {
                return ResourceManager.GetString("MetaDataSymbolTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Time Zone.
        /// </summary>
        public static string MetaDataTimeZoneTag {
            get {
                return ResourceManager.GetString("MetaDataTimeZoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. close.
        /// </summary>
        public static string TimeSeriesCloseTag {
            get {
                return ResourceManager.GetString("TimeSeriesCloseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block day.
        /// </summary>
        public static string TimeSeriesDayTag {
            get {
                return ResourceManager.GetString("TimeSeriesDayTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. high.
        /// </summary>
        public static string TimeSeriesHighTag {
            get {
                return ResourceManager.GetString("TimeSeriesHighTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. low.
        /// </summary>
        public static string TimeSeriesLowTag {
            get {
                return ResourceManager.GetString("TimeSeriesLowTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. open.
        /// </summary>
        public static string TimeSeriesOpenTag {
            get {
                return ResourceManager.GetString("TimeSeriesOpenTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. volume.
        /// </summary>
        public static string TimeSeriesVolumeTag {
            get {
                return ResourceManager.GetString("TimeSeriesVolumeTag", resourceCulture);
            }
        }
    }
}
