//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaVantage.Common.Models.TechnicalIndicators.STOCHRSI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AvSTOCHRSIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AvSTOCHRSIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaVantage.Common.Models.TechnicalIndicators.STOCHRSI.AvSTOCHRSIRes", typeof(AvSTOCHRSIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastD.
        /// </summary>
        public static string BlockFastDTag {
            get {
                return ResourceManager.GetString("BlockFastDTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastK.
        /// </summary>
        public static string BlockFastKTag {
            get {
                return ResourceManager.GetString("BlockFastKTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd hh:mm:ss.
        /// </summary>
        public static string MetaDataDateTimeFormat {
            get {
                return ResourceManager.GetString("MetaDataDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.3: FastD MA Type.
        /// </summary>
        public static string MetaDataFastDMATypeTag {
            get {
                return ResourceManager.GetString("MetaDataFastDMATypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.2: FastD Period.
        /// </summary>
        public static string MetaDataFastDPeriodTag {
            get {
                return ResourceManager.GetString("MetaDataFastDPeriodTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.1: FastK Period.
        /// </summary>
        public static string MetaDataFastKPeriodTag {
            get {
                return ResourceManager.GetString("MetaDataFastKPeriodTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2: Indicator.
        /// </summary>
        public static string MetaDataIndicatorTag {
            get {
                return ResourceManager.GetString("MetaDataIndicatorTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4: Interval.
        /// </summary>
        public static string MetaDataIntervalTag {
            get {
                return ResourceManager.GetString("MetaDataIntervalTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3: Last Refreshed.
        /// </summary>
        public static string MetaDataLastRefreshedTag {
            get {
                return ResourceManager.GetString("MetaDataLastRefreshedTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7: Series Type.
        /// </summary>
        public static string MetaDataSeriesTypeTag {
            get {
                return ResourceManager.GetString("MetaDataSeriesTypeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1: Symbol.
        /// </summary>
        public static string MetaDataSymbolTag {
            get {
                return ResourceManager.GetString("MetaDataSymbolTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5: Time Period.
        /// </summary>
        public static string MetaDataTimePeriodTag {
            get {
                return ResourceManager.GetString("MetaDataTimePeriodTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8: Time Zone.
        /// </summary>
        public static string MetaDataTimeZoneTag {
            get {
                return ResourceManager.GetString("MetaDataTimeZoneTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to block day.
        /// </summary>
        public static string STOCHRSITag {
            get {
                return ResourceManager.GetString("STOCHRSITag", resourceCulture);
            }
        }
    }
}
